### ISSUE TITLE
Story - 2 - Add Images to Recipe List

### ISSUE THREAD

**Issue by carolinstuhr** [carolinstuhr/capstone-project#3]
#### Value Statement
As a user I would like to see an image of the recipe in order to get a better understanding/imagination of each recipe

#### Description
- Add image above the recipe name & descriptive points

![Story 2](https://user-images.githubusercontent.com/26010909/80714381-26c09f80-8af5-11ea-843b-c8bda8782260.jpg)

#### Acceptance Criteria
- [ ] Image & Recipe name should visually be grouped together
- [ ] Separation between individual recipes should still be clearly visible

#### Tasks
- [ ] Create image folder and add to it all the images
- [ ] Add link to image for each recipe in JSON
- [ ] Add styling & positioning for the images

#### Size
Small
