### ISSUE TITLE
Story - 3 - Add Page With Details For Each Recipe

### ISSUE THREAD

**Issue by carolinstuhr** [carolinstuhr/capstone-project#4]
#### Value Statement
As a user I need to see the details for each recipe in order to recreate them

#### Description
- Adding a detailed recipe overview for each recipe
- picture at the top
- name & key points (duration, amount of people) in the middle
- ingredients and instructions
- you can switch between seeing the ingredients and instructions by clicking the respective word

![Story 3 - 1](https://user-images.githubusercontent.com/26010909/80714843-caaa4b00-8af5-11ea-97b3-716cdc1cacab.jpg)

![Story 3 - 2](https://user-images.githubusercontent.com/26010909/80714901-e01f7500-8af5-11ea-804b-24952a2d698b.jpg)

#### Acceptance Criteria
- [x] on Recipe click (includes all image, name, and descriptive points) open the recipe details page (currently without any animation)
- [x] by clicking the x in the top left corner return to all recipes page
- [x] by clicking either on ingredients or instructions display either the ingredients or instructions (currently without any animation)
- [x] Instructions are numbered starting at 1.

#### Tasks
- [x] create feature branch
- [x] create Components: RecipeDetails
- [x] Add React Router
- [x] Add on click events for:
    - [x] each recipe
    - [x] closing of recipes (x)
    - [x] changing between ingredients and instructions
- [x] Add styling (layout) to the recipe details page
- [x] Include the keypoints, ingredients and instructions in the json
- [x] Add component to App.js
- [x] Add component tests

#### 
Size
Medium
