### ISSUE TITLE
Story 4 - Add Filter To Recipe List

### ISSUE THREAD

**Issue by carolinstuhr** [carolinstuhr/capstone-project#5]
#### Value Statement
As a user I need to filter the recipe in order to find specific recipes more quickly

#### Description
- Adding a filter bar at the top of the recipe list, so that when the user types in a name it filters the results (for both name and descriptive points)

![Story 4](https://user-images.githubusercontent.com/26010909/80716566-13fb9a00-8af8-11ea-832e-51981acc3357.jpg)

#### Acceptance Criteria
- [ ] on Input the displayed recipes change to the user input (this takes the names and the descriptive points into consideration)
- [ ] The recipes keep their onClick event to get to the details page
- [ ] the input field will only be visible when at the top, when scrolling down it will be part of the scroll and not be visible

#### Tasks
- [ ] Create feature branch
- [ ] create input field with an on Input event
- [ ] filter results when user types
- [ ] Add unit test to see what results are displayed when user types in uncommon combinations (names that don’t exists, numbers, symbols)

#### Size
Medium
