### ISSUE TITLE
Story - 5 - Add Favourites Icon And Favourites List

### ISSUE THREAD

**Issue by carolinstuhr** [carolinstuhr/capstone-project#7]
#### Value Statement
As a user I need to be able to save favourites in order to save time when trying to find my favourite recipes again

#### Description
- Add a heart icon at the top right corner of the detail Recipe page
- Add a minimal switch navigation at the top of the recipes to switch between All and Favourites
- The Search Option should be available in both

![Story 5 - 1](https://user-images.githubusercontent.com/26010909/80861455-f69d0c00-8c6e-11ea-8794-130f1bac67db.jpg)
![Story 5 - 2](https://user-images.githubusercontent.com/26010909/80861456-f866cf80-8c6e-11ea-9bef-9eddd9fc965c.jpg)

#### Acceptance criteria
- [ ] When the user clicks the heart symbol it will be coloured in
- [ ] A user can click on the heart of a recipe in order for the recipe to be added to the favourites list
- [ ] By clicking on the switch navigation you will be redirected to either the favourites or all recipes
- [ ] If the user doesn’t have any favourites yet, the favourites site will display 'You haven’t selected any favourites yet'
- [ ] The search-bar logic works the same for all recipes and favourites

#### Tasks
- [ ] Create feature branch
- [ ] Create component 
- [ ] Save favorites of user in local storage
- [ ] Add default for when no favourites have been selected
- [ ] Add navigation at the top & and heart symbol to recipe details
- [ ] Component testing

#### Size
Medium
