### ISSUE TITLE
Story - 6 - Create A New Recipe

### ISSUE THREAD

**Issue by carolinstuhr** [carolinstuhr/capstone-project#9]
#### Value Statement
As a user I need to be able to create new recipes to have all my recipes in one place

#### Description
- Add + symbol at the bottom right corner of the recipes page
- Add a new page where you can create new recipes with input fields for
    - Title of recipe
    - 3 descriptive tags
    - time (it takes to cook)
    - portion size
    - ingredients - two input fields, one for the amount and one for the name of the ingredient
    - instructions - numbered automatically starting at one
    - ingredients and instructions have + symbol at the bottom to add additional line
    - Upload picture from local machine button
- submit button
- top left has a return to previous page symbol

![Story 6 - 1](https://user-images.githubusercontent.com/26010909/80864028-34eef700-8c80-11ea-8f02-6908dd1d3f44.jpg)
![Story 6 - 2](https://user-images.githubusercontent.com/26010909/80864031-37e9e780-8c80-11ea-982c-17ad8ecfd0a4.jpg)

#### Acceptance Criteria
- [ ] When clicking on the create symbol the user should be taken to the create page (without animation)
- [ ] The input fields have these restrictions:
    - [ ] title: min 2, max 30 letters
    - [ ] descriptive tags: min 2 letters, max 15 letters per tag, max 3 tags
    - [ ] portion size: user can select from one of the given options by clicking on one number
    - [ ] time: has to be a number, first number is the hour, second the minutes (both max 2 numbers)
    - [ ] ingredients: left  field min 1, max 6 letters, right: max 20 letters
    - [ ] number of ingredients: min 1, max 30
    - [ ] instructions: min: 10 letters, max 200 letters
    - [ ] max 30 instructions
    - [ ] by clicking on + below ingredients/instructions a new line for the respective element should be added for the user to fill out
- [ ] When clicking on the upload image button a window should pop up, asking the user to select an image from his local files
- [ ] the user should be able to pick up these file types: png, jpeg, pdf
- [ ] when the user doesn’t upload an image a default image will be set and displayed 
- [ ] When submitting the created recipe it should be included in the all recipes overview and in the favourites of the user and the user should be redirected to the recipes home page
- [ ] when the user clicks on the top left return to previous page symbol the information that has been entered so far will be deleted

#### Tasks
- [ ] Create feature branch
- [ ] Save new recipes to local storage - only the user will be able to see them
- [ ] Create new component: CreateRecipe
- [ ] Create input form element  - with restrictions on what the user can enter and what not
- [ ] Add styling for the Create Page
- [ ] Add component to App.js
- [ ] Enable user to upload a picture from his computer (virus scan?)
- [ ] Component Testing

#### Size
Large
